apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-s3-credentials
  namespace: argo
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argo-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: cicd-argo-s3
        property: access_key
    - secretKey: secretkey
      remoteRef:
        key: cicd-argo-s3
        property: secret_key
