apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-s3-credentials
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: argo-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: grizzly-platform/cicd/argo-s3
        property: access_key
    - secretKey: secretkey
      remoteRef:
        key: grizzly-platform/cicd/argo-s3
        property: secret_key
