apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy-daemonset.yaml
  - flux-external-scraping.yaml
  - flux-metrics-services.yaml
