apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: career-scanner
  namespace: flux-system
spec:
  interval: 5m
  releaseName: career-scanner
  targetNamespace: career-scanner
  chart:
    spec:
      chart: ./deploy
      sourceRef:
        kind: GitRepository
        name: career-scanner
        namespace: flux-system
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
